### ISSUE TITLE
Use commitizen + semantic release

### ISSUE THREAD

**Issue by jpnelson** [skatejs/build#179]
I'd use the guide here: 
https://github.com/commitizen/cz-cli with conventional changelog

and after that's set up, the default set up for semantic release should read that commit log and make releases.

https://github.com/semantic-release/semantic-release with the conventional changelog commit analyzer should do the actual releases.

There'd need to be some travis-ci integration to enable it, @joscha has set up the atlassian/lerna-semantic-release to release on travis-ci with semantic-release and commitizen, so he should know what to do there. That said, from what I've seen, the semantic-release guide is pretty easy to set up travis-ci with. We can use the pre and post steps directly from semantic-release.

I'd use as much of the defaults as possible. They're pretty well set up for github, we could generate releases and release notes in the same way.

**Comment by joscha** [comment]
There is a CLI tool from semantic release that creates almost everything automatically, it's part of the README of their github project. Adding conventional changelog itself is done via commitizen:

```
npm install commitizen -g
commitizen init cz-conventional-changelog --save-dev --save-exact
```

**Comment by joscha** [comment]
I think the conventional changelog config needs to go in each package.json, same as for the travis build, so I am not sure you can do it in this repo alone. As you need to keep the versions in sync with the config adding them to this repository might not be the way to go.

**Comment by jpnelson** [comment]
Yeah I'm not sure how that's going to work. At the least, the `semantic-release pre` / `semantic-release post` steps can replace `bin/release` here

**Comment by treshugart** [comment]
This is done now. It exposes the proper commands for doing this as well as boilerplate files that include the integration. All repos need to do is do `semantic-release-cli setup` or whatever that is. Skate is now using this, too!
